### ISSUE TITLE
Training Error in Loss.py

### ISSUE THREAD

**Issue by mohamad9372** [giuliomattolin/ConfMix#11]
Hi, Thanks for answering.
I'm facing with this error in the beginning of training.

Epoch   gpu_mem       box       obj       cls    labels  img_size
  0% 0/950 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/ConfMix/ConfMix/train.py", line 676, in <module>
    main(opt)
  File "/content/drive/MyDrive/ConfMix/ConfMix/train.py", line 571, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/drive/MyDrive/ConfMix/ConfMix/train.py", line 358, in train
    loss, loss_items = compute_loss(pred, targets.to(device), var)
  File "/content/drive/MyDrive/ConfMix/ConfMix/utils/loss.py", line 125, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/content/drive/MyDrive/ConfMix/ConfMix/utils/loss.py", line 234, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type long int

How can I fix it?

**Comment by giuliomattolin** [comment]
Hi @mohamad9372,

A possible solution to this error has been previously mentioned in https://github.com/giuliomattolin/ConfMix/issues/10#issuecomment-1666779620.

Let me know if this solves your problem.
