### ISSUE TITLE
Model pretrain YOLOv5 casting error

### ISSUE THREAD

**Issue by RosiYo** [giuliomattolin/ConfMix#14]
## Situation
Trying to replicate the model pre-training stage for the case Cityscapes -> FoggyCityscapes results in a casting crash. For replicating, just follow the instructions on the github using conda installation.

## Obtained Traceback
_Note: Home folder route has been substituted for `$HOME` for privacy reasons_

```
Traceback (most recent call last):
  File "train.py", line 676, in <module>
    main(opt)
  File "train.py", line 571, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 358, in train
    loss, loss_items = compute_loss(pred, targets.to(device), var)
  File "$HOME/ConfMix/utils/loss.py", line 125, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "$HOME/ConfMix/utils/loss.py", line 234, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type long int
```

## In addition
After a quick search in Google, it seems like YOLOv5 could need to be updated for solving this problem ([Related Github thread](https://github.com/ultralytics/yolov5/issues/8405)). However, I have not been able to update it manually.

**Comment by RosiYo** [comment]
I have just found out #10 has a solution for this case. Sorry for the trouble.
